"""Sync dashboard

Revision ID: 167ea358893d
Revises: 7c689b4555df
Create Date: 2026-06-06 15:30:28.999730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167ea358893d'
down_revision = '7c689b4555df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_agents_email'), ['email'])

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_tickets_ticket_number'), ['ticket_number'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tickets_ticket_number'), type_='unique')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_agents_email'), type_='unique')

    # ### end Alembic commands ###
