"""Add missing ticket columns

Revision ID: 7c689b4555df
Revises: 
Create Date: 2026-06-06 13:13:39.150773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c689b4555df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_agent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('emotion', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_tickets_assigned_agent_id', 'agents', ['assigned_agent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('closed_at')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('emotion')
        batch_op.drop_column('assigned_agent_id')

    # ### end Alembic commands ###
